### ISSUE TITLE
cleanup UDP interface/implementation

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1079]
We have:
- arch/linux/mcu_periph/udp_arch.[ch]
- fms/fms_network.[ch]
- modules/computer_vision/lib/udp/socket.[ch]

**Comment by fvantienen** [comment]
From the top of my head only "arch/linux/mcu_periph/udp_arch" is used now in the airborne code. Except for some computer vision modules. Fms can be removed totally if I'm correct.
I think the "arch/linux/mcu_periph/udp_arch" is the way to go, because it has the same interface as in UART etc. So you can switch between those 2 easily.

Next to this we should also check own socket implementations, which don't use any of these and replace those to make it nicer.

**Comment by flixr** [comment]
@fvantienen fms_network is still used in natnet2ivy...
I tried to convert to use udp_socket instead with https://github.com/flixr/paparazzi/commit/638fc0f2a7fcef3cd23c3df6780497f90346c963, would be nice if you could confirm that natnet2ivy still works...

**Comment by OpenUAS** [comment]
Needs testing in Cyberzoo. Will re-assign or report if not working

**Comment by flixr** [comment]
should be finally closed with merge of #1162 which removed the fms stuff
