### ISSUE TITLE
improve cam handling

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#172]
The cam_point module
- sends the CAM message, with camera orientation (roll,pitch) and target xy coordinates.
- server calculates Lat/long from the CAM message and sends CAM_STATUS ground message
- you can enable the cam footprint in the GCS (reads CAM_STATUS)

The difference of using SHOW_CAM_COORDINATES and the CAM_POINT message is that you already get the coordinates in lat/lon via telemetry, but apparently can't show the cam footprint in the gcs...

Currently missing:
- the CAM message is only read for fixedwings (server_fw.ml)
- only handes cameras that can move in roll/pich axes, but not ones that can move around yaw (look left/right).
- cam_aperture (also aspect ratio) is hardcoded in live.ml... this should really be settable via option.
##

**Comment by rijeshaugustine** [comment]
I've been looking into this.

I have one other quam with the current implementation.
At ground level the cam footprint still shows a large square footprint, this seems to indicate that height is not being taken into account. 

I reworked the module so that it would read a Horizontal angle of view and a vertical angle of view from the airframe file. 

I was unclear as to the purpose of all the processing that was happening in server.ml. I fly without a gimbal so only have to worry about the angles of the airplane.
Currently I have the CAM_STATUS message being used to trigger the cam update but don't actually read the contents of the message. 
Finally I used a polygon shape rather than a rectangle to plot the footprint. 
https://github.com/rijeshaugustine/paparazzi/commit/159134aa9bb998a92cbc3525eaa4d76e200f29e1

This commit removes the functionality of camera roll/pitch. If camera roll/pitch were sent in CAM_STATUS (rather than lat and long) this could easily be incorporated into the current math.
I have simplified the code significantly. Am I missing something by doing so? Essentially I am using the field of view and angles of the airplane to find the centre point of each line segment of the footprint and then getting the 4 corners. 

I've also had a look at getting camera yaw incorporated. I was thinking there could be a quaternion for the camera angles and a quaternion for the plane angles. Multiply them together and convert back to angles. I'm not sure if this will work though due to the order the rotations happen. I would imagine that both yaw rotations would have to be dealt with first and then pitch and roll can be dealt with.

**Comment by rijesha** [comment]
This issue is almost solved, just need a little bit more information.
The cam message only being read by fixedwings has been fixed already.
Pull Request #2103 has the relevant GCS code for cam_aperture and a fully gimbaled camera.

https://github.com/rijesha/paparazzi/blob/68dec2251cb4dec76ed38f8548203d40d514357a/sw/ground_segment/tmtc/server.ml#L178
This line is where phi theta psi of the camera gimbal should go. Currently the aircraft only sends phi and theta. The documentation on the wiki is somewhat confusing for this. A true pan and tilt camera would require a psi. 

The quaternion takes tait-bryan angles. By default the camera is pointed straight down. (So to point the camera in the direction of flight theta = 90deg, phi = 0deg, psi = 0deg)

So to complete this issue we will need to send psi from the aircraft and standardize what phi/theta/psi mean.

**Comment by gautierhattenberger** [comment]
It seems that cam phi refers to pan and cam theta to tilt (https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/cam_control/cam.c#L249). So they are not really euler angles. In order to determine phi/theta/psi or a quaternion from this, I guess you need to now how the camera and the servos/motors are assembled I guess ? Anyway, not sure the psi is really needed here, maybe renaming properly the messages field if they are actually wrong.

**Comment by rijesha** [comment]
Ok. I was checking out the wiki (https://wiki.paparazziuav.org/wiki/Pan_Tilt_Camera) and there are references to a one axis pitch, a one axis roll, and a two axis camera. I have no real preference to how this should be implemented (maybe I will if I every use a gimbal), I will just rename the variable to make it more meaningful.

**Comment by rijesha** [comment]
Wrote a little bit about the modifications here: http://wiki.paparazziuav.org/wiki/Cam_Footprint
