### ISSUE TITLE
GCS Crashes on Ubuntu 16.04 when using papgets in layout file

### ISSUE THREAD

**Issue by deonblaauw** [paparazzi/paparazzi#1823]
GCS segmentation fault occurs when there are papgets in the GCS layout file. This happens on Ubuntu 16.04. The crash occurs immediately when telemetry is received. When no telemetry is received, GCS does not crash, but papgets also do not display.

**Comment by dewagter** [comment]
I confirm I have had this too (only on ubuntu16): layout horizontal.xml
works but bottom_settings.XML gives a segfault in the GCS.

**Comment by flixr** [comment]
Hm... very weird.
Works fine with e.g. papgets.xml on our 16.04 pprz-dev Docker image, but then it's using the X-Server of my Ubuntu 14.04 host...

Could someone with native 16.04 maybe try to dig deeper? Run it in gdb or so...

**Comment by dewagter** [comment]
@openuas could you try it on the field laptop with gdb?

**Comment by OpenUAS** [comment]
Yes, even on development laptop ...so I have the  .crash file and I will try something like:
https://wiki.ubuntu.com/DebuggingProgramCrash

GCS does however it doesshow papgets for a second or so
![gcs_still_shows_papgets_then_crashes ](https://cloud.githubusercontent.com/assets/483944/17355450/06684b7c-5951-11e6-929a-00c3bd917a4a.png)
 but I have the hunch that after TELEMETRY comes in play the GCS crashes...

...ongoing , everyone is frree to join ;) with their debugging since this week there are some other urgent task..
