### ISSUE TITLE
Calling AbiBindMsgRPM twice leads to unresponsive system

### ISSUE THREAD

**Issue by EwoudSmeur** [paparazzi/paparazzi#1924]
Noticed on a bebop1. After telnetting I could see that a printf in the callback gave a lot of output, but I did get any telemetry. When I make sure AbiBindMsgRPM is called only once I have no problem.

I know the function is not supposed to be called twice, but I also think it should not make the system unresponsive.

**Comment by flixr** [comment]
Hm... I don't see how that could be a problem with ABI itself.
If you call AbiBindMsgX multiple times, it will simply call the callback function multiple times (with the one bound last called first).
You can see that in the generated var/include/abi_messages.h

So I think the cause is somewhere else... maybe depends on what you do inside the callback?

**Comment by flixr** [comment]
Or are you re-using the same abi_event for the second bind?
I guess that would create an endless loop as the event will add itself as next in the linked list...
