### ISSUE TITLE
realtime plotter spams warnings (ubuntu 16.04)

### ISSUE THREAD

**Issue by EwoudSmeur** [paparazzi/paparazzi#1936]
The realtime plotter typically spams this warning for me:
(plotter:31131): GLib-GObject-WARNING **: value "-nan" of type 'gdouble' is invalid or out of range for property 'lower' of type 'gdouble'

It does not matter if I turn autoscale on or off.

Other than that it works fine. But now I can not see anything that happens in paparazzi center...

**Comment by podhrmic** [comment]
Same thing here:(

**Comment by podhrmic** [comment]
Update - the warning comes from this line in glib: https://github.com/GNOME/glib/blob/master/gobject/gobject.c#L1414

And indeed, this is caused by the ocaml plotter https://github.com/paparazzi/paparazzi/blob/master/sw/logalizer/plotter.ml - it triggers the warning when it a message is not received (lets say telemetry is lost), but time is still going so the plotter gets updated with nan values. Can't find out where it is being called though. Any insights from our Ocaml gurus @flixr @gautierhattenberger ?

**Comment by podhrmic** [comment]
Update - it happens also when the same value is updated (lets say you are plotting a battery voltage and it is not changing, but it is being received from a message) -> still the warning...

**Comment by gautierhattenberger** [comment]
Hopefully this was the only source of warnings...
