### ISSUE TITLE
GCS and RealTime plotter crash in Ubuntu 16.04

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2041]
Randomly and after a relative short time, GCS and Real Time Plotter silently crash in Ubuntu 16.04. Looks like OCaml or GTK+ is not a friend with the Ubuntu - can we resolve this somehow?

Having the GCS crash makes it hard to use for longer missions (operators get surprised when the GCS has to be restarter).

**Comment by flixr** [comment]
I cannot reproduce this issue.... at least not is simulation, but that should make no difference as the data you get there is the same or actually even more...

**Comment by podhrmic** [comment]
I ll investigate over the weekend and post more info.

**Comment by podhrmic** [comment]
Here is what I have from a crashed plotter:
```
RUN '/home/podhrad/Documents/Paparazzi/paparazzi/sw/logalizer/plotter '

** (plotter:21284): WARNING **: (../../../lib/unity-gtk-action-group.c:355):unity_gtk_action_group_really_change_action_state: code should not be reached

** (plotter:21284): WARNING **: (../../../lib/unity-gtk-action-group.c:363):unity_gtk_action_group_really_change_action_state: code should not be reached
 Read Socket : Connection reset by peer

STOPPED '/home/podhrad/Documents/Paparazzi/paparazzi/sw/logalizer/plotter'
```

**Comment by flixr** [comment]
Hm... have never seen that before... Do you have steps to reproduce this?

**Comment by kevindehecker** [comment]
I have the same problem (at least with GCS). Disabling the battery read outs that the tudelft conf has by default made it much better (now crashes only once an hour or so, instead of after a few minutes tops). Not sure if related.

My steps to reproduce are basically: start GCS and wait for it.... Can reproduce in sim just as easily as with real drone, but the timing is completely random. (so the sim does not crash at the same time as with the real drone). Running the same logs etc on another computer does not crash it at all.

Does your laptop have a touchscreen by any chance? My laptop is, and our Outback field laptop is touched as well (literally and figuratively).

**Comment by gautierhattenberger** [comment]
As a side note, I'm running Kubuntu 16.04 and I've never seen this. So the error is most likely related to unity as the error message suggests.

**Comment by podhrmic** [comment]
I am running it on ThinkPad Carbon X1, but I ll try to use Gnome instead of Unity and see if it makes a difference.

**Comment by flixr** [comment]
I'm also running unity and haven't been able to reproduce this with a simulation of Quad_LisaMX

**Comment by OpenUAS** [comment]
Using Default Ubuntu 16.04.2 but also xubuntu  and mint on a touchscreen enabled devices. Running GCS for hours on end and with all kind of plotters tools etc. Never had an GCS crash since years. It is extremely annoying indeed. I run the GCSand all tools on at least a dozen different PC's even under OSX native, no issue. If you need testing help, make a not on this issue or gitter plz.

**Comment by noether** [comment]
Xavier and me have the same problem. Ubuntu 16.10 and unity for me and Xavier with Kubuntu .

**Comment by noether** [comment]
just fyi. It is still crashing in 17.04
any suggestion about how can I log the session, so in case it crashes again you can look at it?

**Comment by gautierhattenberger** [comment]
Some updates here regarding GCS crashes: I have
- a laptop with Kubuntu 16.04 (KDE) that is working perfectly
- a laptop with Ubuntu 16.04 (Unity) that is crashing really fast each time

Running with debugger gives a segfault and this kind of information:
```
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
```
Also, it seems that it is always related to graphical element update from IVY callbacks. So there is a chance that Ivy ends up in a different thread than the Gtk canvas elements and that the thread protection is not properly done. But this doesn't explain why it was working before and why it has different behaviors between computers (and my colleagues have issues with KDE, so it is not related).

I tried to implement the `XInitThreads` call before running the GCS main loop. On the working laptop, it makes no difference (still working), on the other one, it is just crashing straight at startup...

As a conclusion: I'm even more confused than before...

**Comment by podhrmic** [comment]
Update: this issue seems to be better ( at least I haven't seen any crash recently) with the recent Ubuntu updates. Proposing closing this issue as resolved?

**Comment by kevindehecker** [comment]
Yeah, it seems to have solved itself :)

**Comment by noether** [comment]
Yes, I agree. Magically I did not experience this issue for a looong time.

**Comment by gautierhattenberger** [comment]
cross fingers for 18.04LTS !
