### ISSUE TITLE
Suggestions on how to implement navigation/guidance/stabilization for an overactuated vehicle

### ISSUE THREAD

**Issue by alessandro-mancinelli** [paparazzi/paparazzi#2844]
Hi everyone  (@gautierhattenberger, @dewagter),
Nice to meet you all, I am Alessandro Mancinelli and I am the PhD student at TUDelft (MAVLab) and my supervisors are Ewoud and Bart. 
In the last year I have been working on a new kind of quadplane with double axis tilting mechanism. It is therefore able to achieve 6 DOF control in the hovering flight condition. 
So far I have been implementing my modules in a very dirty way due to lack of time. I now would like to implement a module for the control of my vehicle using the paparazzi framework properly. However, while discussing with Ewoud, we had quite few doubts on how to interface my framework with the actual structure of paparazzi. My vehicle does not always need an outer loop to run, being able to achieve 6DOF directly. Also, I developed a custom Control Allocation module which runs externally on a raspberry pi. I was wondering on how to structure the navigation/guidance/stabilization modules for my vehicle. Any suggestions and comments are more than appreciated! 
The repository of the vehicle airframe is quadplane-plus and it is on the overactuated_vehicle_gen_2 branch : 
(https://github.com/tudelft/paparazzi/tree/overactuated_vehicle_gen_2).
In particular, the main module which implements the vehicle control is the Overactuated_vehicle module: (https://github.com/tudelft/paparazzi/tree/overactuated_vehicle_gen_2/sw/airborne/modules/Overactuated_vehicle).
Feel free to ask me anything and thank you in advance!

**Comment by noether** [comment]
Hi Alessandro,

The definition/architecture of GNC is always tricky since some elements can fit (or overlap) into the three blocks (Guidance, Navigation, and Control). In the end, it highly depends on the project/vehicle and the developers.

Typically, once the "subsystems" (now modules in Paparazzi :P) are set, then the interconnections are clear, and their implementations as well (software layers, messages with setting points/signals, etc). Since Paparazzi right now covers different kinds of vehicles, I do not think it is possible to have something like that fixed, and you have some freedom indeed. I believe @gautierhattenberger has something in mind on how to design a "flexible" GNC, allowing you to have even different controllers for the same states/vehicles so you can change them online. I believe he is working on that within the new version 6 of Paparazzi. Probably, he can tell you more about how to structure your GNC for your vehicle.

While possible of course, I do not think the main focus is on supporting "low level" routines, such as the control, outside of the corresponding microcontroller. Especially, for those tasks that need to be 100% deterministic and predictable.

**Comment by gautierhattenberger** [comment]
Hello,
If you want to run a GNC stack that doesn't fit into the default structure, a possibility is to use the autopilot generation functionallity that is described here: https://wiki.paparazziuav.org/wiki/Autopilot_generation
You have some examples in the folder `conf/autopilot`. In particular, you should start from the `rotorcraft_autopilot.xml` file that is a reduced version of the default static autopilot.
There are some limitations when using this, like some modes are expected (at least they need to be defined) to build the autopilot. If you actually need these mode, you can leave them empty and remove the `select` node, so they are never called.
This is still experimental, so you might have some issues while compiling or connecting the different elements. Don't hesitate to ask for clarification or help on Gitter or Github.

**Comment by EwoudSmeur** [comment]
Thanks for your comments! Indeed I thought this could be a good use case for the autopilot generation, so it would be interesting to give it a try!
