### ISSUE TITLE
Semaphore fails because of cryptographic library

### ISSUE THREAD

**Issue by Fabien-B** [paparazzi/paparazzi#2963]
Semaphore builds are failing with the Iris airframe in the `aggieair_conf.xml` conf with this error:
`ext/hacl-c/kremlib.h:513:33: error: expected ')' before 'PRIx64'`

I don't know why it stopped working, it tried adding `__STDC_FORMAT_MACROS` but it had no effects.

Could you take a look @podhrmic ?

**Comment by podhrmic** [comment]
Has the GCC version in the CI changed recently? Looking at the code, this is just [a GCC kludge](https://github.com/paparazzi/hacl-c/blob/bca1a10ddc9bf6844b8b3ab1f895070523edd149/kremlib.h#L92) and shouldn't be even needed for paparazzi, since we are not really debug-printing. You can either remove the offending code, or I am happy to do it.

**Comment by Fabien-B** [comment]
Fixed in #2967
