### ISSUE TITLE
prettyfy/improve (sub)programs handling in paparazzi-center

### ISSUE THREAD

**Issue by esden** [paparazzi/paparazzi#4]
(originally submitted by poinix)

The "session" functionality is awsome. But having to configure program by editing command line is ... not user friendly, plus the most complex things most people do is selecting a serial device or a baudrate. There already exists a description of some command line options along with program in the xml configuration ( conf/control_panel.xml ) , we could complete that description and replace/complements the text input for editing command line in paparazzi-center with a dialog box allowing to select options ( eg serial ports, baudrates) from dropboxes.

We could maybe even got further and put the "dialog box" as pages of a notebook widget, the "start/stop" button becoming a red/green LED next to the short name of the program in the tab of the notebook.

It would make it less error prone for beginners and make it more abstract for casual users that they are running several programs. They are just switching on and off parts of paparazzi.

The change of one parameter could enforce a program restart ( which is not done at the moment with the text editing )

**Comment by OpenUAS** [comment]
I rather not have a program restart after editing, most of the time  I add parameters to be able to start it at the very moment I would like it.

With the Linux GUI option "icons on button" could already be considered "led"

ON the whole improving it is sure a welcomed addition, however the session was quickly understood and used my experienced guiding 100+ of students.

**Comment by kevindehecker** [comment]
I think the whole design of pprz center is completely backwards and needs heavy rethinking. It attempts to be an IDE, but lacks critical IDE features and on the same time adds features that should not be handled by an IDE. Simple examples of those:

1. Center shows the compilation output, but it is impossible to double click the error and go there in the editor
2. Opening plots and messages for flight analysis during operation is not something you'd normally want to do from the IDE, but here this is supposedly the flow of things.

Center is a GUI clearly written by people who very much liked to edit command line options and xml files. But, the main goal/improvement of a GUI over command line is not help editing these options, it is to provide the user hints on what relevant options exist (show, don't remember). At this point, using Center is about as easy as just working from the command line and edit the xml manually to start with (which I regularly do, and I'm sure those 100 students would pick up just as fast). Actually, even for this I really don't see any major advantage of Center here. 

Here is what I think. I don't think it is the task of the pprz team to write an actual proper IDE. Instead, we should actively support using a common existing IDE for ap development. Those existing IDE's (e.g. Eclipse) won't support all UAV specific stuff mainly related to setting up a flight like connecting joysticks and what not, but this should be moved to GCS using the nice settings dialog GUI proposed in this issue that is. Current Center sessions should also simply be supported directly from GCS, which makes way more sense. And sure, for the advanced features one should for now always be able to edit the xml files directly.

**Comment by flixr** [comment]
Paparazzi Center is NOT supposed to be an IDE!

And personally I absolutely disagree that the sessions and things like connecting joysticks should be integrated into the GCS, these are totally separate things and don't even need to run on the same host.

**Comment by kevindehecker** [comment]
Not supposed yes, still attempting. This is exactly my point...

Sure, I don't know all GCS' use cases, but the one we are using here like 99% of the time actually does run on the same host which should count for something. In any case, if you start calling out implementation details (which I'm can be fixed in some way), you are very sure to win this discussion because clearly you have much more knowledge about pprz. So, instead of defending this proposal, my first question is, do you recognize the the problem I have with the current program flow? Because if not, we clearly have a gap between users and programmers that needs addressing first.

**Comment by flixr** [comment]
In my view the Paparazzi Center is not even attempting to be an IDE... as the name says, an IDE is use for developing.

For me the Paparazzi Center is foremost something to more easily run/supervise multiple processes and to save them in sessions so that you don't have to type it out every time.

About integrating other parts in the GCS:
The GCS is only one part (and an optional part at that) of the ground system.
This is also not an "implementation detail", but a fundamental architectural design decision of using a "pub/sub bus" and distributed agents.
https://wiki.paparazziuav.org/wiki/Overview#System_Architecture

I acknowledge that in a lot of use cases you will run all this on the same host, but this should be no restriction.

We are mixing two different discussions here: how to improve/prettify the paparazzi center and whether we should move things like starting joysticks, etc. to the GCS....

I would welcome the former if it helps people, but not in favour of the latter...

**Comment by gautierhattenberger** [comment]
In addition I would say that the Paparazzi ground station is build on a very different principal compared to other GCS like qgroundcontrol. It is a set of small dedicated tools (server, link, GCS, ...) that are designed to something precise but need to interacts with other elements to actually produce something (this is coming from the Unix world). Other projects usually have a monolithic approach (a single GUI doing everything), eventually with plugins capabilities (a bit more Windows-like approach, so not a big surprise if most people are more comfortable with this).
As Felix said, the PPRZ Center is just a tool that is use to assemble the pieces (elements of an airframe or elements of your ground station), but is supposed to help you develop something. Maybe the "build" button is something misleading for people using an IDE and that still don't know enough about Paparazzi.
It is not really an option to change the way existing tools are working. So, we could imagine to start a completely new ground station, which is I think a waist of time. Either finish Mavlink integration and use qgroundcontrol or make a new GCS that respects the current architecture (so a pure HMI for A/C control, nothing else). Hopefully both will happen some day.
An other option would be to make a lighter version of the center that hides some misleading elements by default: hide console, command line option, rename some buttons
An also make a better documentation... maybe a schematics explaining a bit better what it is suppose to do ? The help of "users" is really needed here, because for core developers it is difficult to see what is really not clear.

**Comment by gautierhattenberger** [comment]
Closing this issue. If improvement should be made, it will not be done in the ocaml. Alternatively, the python version (#1811) can be used as a start and improved.
