### ISSUE TITLE
Gtk-CRITICAL messages not filtered in paparazzicenter

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#895]
As a user of paparazzicenter I ony want to see information relevant to my software use. A user could get insecure if he sees a message e.g. 

(paparazzicenter:7882): Gtk-CRITICAL **: IA__gtk_container_remove: assertion `GTK_IS_TOOLBAR (container) || widget->parent == GTK_WIDGET (container)' failed

Either we could filter and do not display or fix the assertion

**Comment by gautierhattenberger** [comment]
This kind of GTK error is very difficult or even impossible to solve since it doesn't give much information. It also depend a lot of your system it seems. I don't have any errors like this on debian stable and latest kubuntu, but on ubuntu 12.04, I have an error (different from this one).
If anyone has an idea of where to start, please tell us. But we may not be able to solve this.

Easy solution to hide these warnings: make a desktop icon, so you don't run it directly in a terminal

**Comment by OpenUAS** [comment]
Thank. BTW just to clarify: when I file an issue, the "I" word does not stand for "Me" but for "a generic user". I try to file a little unified issues fitting to agile way of working and handling issues.

**Comment by flixr** [comment]
Unless someone wants to track all this down (most of the warnings actually occur with many GTK apps and can't be avoided from our end), I would say we close this with WONTFIX or at least take it out of this maintenance release milestone....

**Comment by OpenUAS** [comment]
It is not about the Gtk-CRITICAL tracking down, I realize it is to much for an autopilot team to fix GTK issues,, the issue is more about the message appearing in the **PaparazziCenter**. So filtering on this and discarding the text would be an option IMHO

**Comment by flixr** [comment]
As Gautier said, simply don't start paparazzi center from the terminal, but from an icon or via alt-f2.
You can't suppress the output on the terminal unless you redirect all of stderr to /dev/null, which is definitely not what we want...

**Comment by gautierhattenberger** [comment]
Closing this issue as a "won't fix", not really a paparazzi issue (most of the time...) and acceptable solution exists.
